apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spc-project
  name: spc-project
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: spc-project
    spec:
      containers:
      - image: devopseasy/spring-petclinic-pro
        name: spc-project
        ports:
        - name: spc-project
          containerPort: 8282      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spc-project
  name: spc-project
spec:
  type: NodePort
  ports:
    - port: 8282
      targetPort: 8282
  selector:
    name: spc-project
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
